<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Alkesh" name="Default test" tests="3" failures="1" timestamp="26 Jan 2019 19:20:08 GMT" time="5.096" errors="0">
  <testcase name="m1" time="0.021" classname="A.C"/>
  <testcase name="m2" time="1.018" classname="A.C">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.m2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.m2() didn't finish within the time-out 1000
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- m2 -->
  <testcase name="m4" time="4.008" classname="A.C"/>
</testsuite> <!-- Default test -->
